Repository sensein/senselab, pull requests merged in 2024-06, with the labels that each got.

#48 Adding utility functions
  poetry.lock
  pyproject.toml
  src/senselab/audio/tasks/data_augmentation.py
  src/senselab/audio/tasks/preprocessing.py
  src/senselab/audio/tasks/preprocessing_pydra.py
  src/senselab/audio/tasks/speech_to_text_evaluation.py
  src/senselab/audio/tasks/speech_to_text_evaluation_pydra.py
  src/senselab/utils/data_structures/audio.py
  src/senselab/utils/tasks/cca_cka.py
  src/senselab/utils/tasks/cca_cka_pydra.py
  src/senselab/utils/tasks/cosine_similarity.py
  src/senselab/utils/tasks/cosine_similarity_pydra.py
  src/senselab/utils/tasks/cross_correlation.py
  src/senselab/utils/tasks/cross_correlation_pydra.py
  src/senselab/utils/tasks/eer.py
  src/senselab/utils/tasks/eer_pydra.py
  src/tests/audio/tasks/data_augmentation_test.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speech_to_text_evaluation_test.py
  src/tests/utils/data_structures/audio_test.py
  src/tests/utils/tasks/cca_cka_test.py
  src/tests/utils/tasks/cosine_similarity_test.py
  src/tests/utils/tasks/cross_correlation_test.py
  src/tests/utils/tasks/eer_test.py
Labels: enhancement

#50 adding some more API classes (participant, session, dataset)
  poetry.lock
  pyproject.toml
  scripts/experiment7.py
  scripts/experiment8.py
  src/senselab/audio/tasks/features_extraction/torchaudio.py
  src/senselab/utils/data_structures/dataset.py
  src/senselab/utils/hf.py
  src/senselab/utils/tasks/input_output.py
  src/tests/utils/data_structures/dataset_test.py
Labels: enhancement

#52 release 0.2.1 including the new custom interface, pre-processing functions, utility functions
  src/senselab/audio/tasks/features_extraction/torchaudio.py
Labels: release

#53 release 0.2.0
  poetry.lock
  pyproject.toml
Labels: release, minor

#56 Release 0.2.0
  .gitignore
  pyproject.toml
  src/senselab/audio/tasks/features_extraction/opensmile.py
  src/senselab/audio/tasks/features_extraction/opensmile_pydra.py
  src/senselab/audio/tasks/features_extraction/praat_parselmouth.py
  src/senselab/audio/tasks/features_extraction/praat_parselmouth_pydra.py
  src/senselab/audio/tasks/features_extraction/torchaudio.py
Labels: release, minor

#57 organizing classes and functions
  src/senselab/app.py
  src/senselab/audio/data_structures/audio.py
  src/senselab/audio/tasks/data_augmentation/__init__.py
  src/senselab/audio/tasks/data_augmentation/data_augmentation.py
  src/senselab/audio/tasks/features_extraction/opensmile.py
  src/senselab/audio/tasks/features_extraction/opensmile_pydra.py
  src/senselab/audio/tasks/features_extraction/praat_parselmouth.py
  src/senselab/audio/tasks/features_extraction/praat_parselmouth_pydra.py
  src/senselab/audio/tasks/preprocessing/__init__.py
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/preprocessing_pydra.py
  src/senselab/audio/tasks/pyannote_speaker_diarization_pydra.py
  src/senselab/audio/tasks/speaker_diarization/__init__.py
  src/senselab/audio/tasks/speaker_diarization/pyannote_speaker_diarization.py
  src/senselab/audio/tasks/speech_to_text/__init__.py
  src/senselab/audio/tasks/speech_to_text/speech_to_text.py
  src/senselab/audio/tasks/speech_to_text/speech_to_text_evaluation.py
  src/senselab/audio/tasks/speech_to_text_evaluation_pydra.py
  src/senselab/audio/tasks/speech_to_text_pydra.py
  src/senselab/audio/tasks/voice_cloning/__init__.py
  src/senselab/audio/tasks/voice_cloning/voice_cloning.py
  src/senselab/audio/tasks/voice_cloning_pydra.py
  src/senselab/text/tasks/embeddings_extraction/__init__.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transofmers_embeddings_extraction.py
  src/senselab/utils/data_structures/dataset.py
  src/senselab/utils/data_structures/device.py
  src/senselab/utils/data_structures/file.py
  src/senselab/utils/data_structures/huggingface.py
  src/senselab/utils/decorators.py
  src/senselab/utils/functions.py
  src/senselab/utils/tasks/cca_cka.py
  src/senselab/utils/tasks/cca_cka_pydra.py
  src/senselab/utils/tasks/cosine_similarity.py
  src/senselab/utils/tasks/cosine_similarity_pydra.py
  src/senselab/utils/tasks/cross_correlation.py
  src/senselab/utils/tasks/cross_correlation_pydra.py
  src/senselab/utils/tasks/eer.py
  src/senselab/utils/tasks/eer_pydra.py
  src/senselab/utils/tasks/input_output.py
  src/senselab/utils/tasks/input_output_pydra.py
  src/senselab/video/data_structures/video.py
  src/senselab/video/tasks/input_output.py
  src/senselab/video/tasks/input_output_pydra.py
  src/tests/audio/data_structures/audio_test.py
  src/tests/audio/tasks/data_augmentation_test.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speech_to_text_evaluation_test.py
  src/tests/utils/data_structures/dataset_test.py
Labels: release, minor

#62 ref: adjust poetry to install opensmile dependency
  .github/workflows/docs.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  pyproject.toml
Labels: release, patch

#60 Adding voice cloning API
  pyproject.toml
  src/senselab/audio/tasks/plotting/plotting.py
  src/senselab/audio/tasks/speech_to_text/api.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/speech_to_text/speech_to_text.py
  src/senselab/audio/tasks/speech_to_text/transcript.py
  src/senselab/audio/tasks/voice_cloning/api.py
  src/senselab/audio/tasks/voice_cloning/knnvc.py
  src/senselab/audio/tasks/voice_cloning/voice_cloning.py
  src/senselab/utils/data_structures/huggingface.py
  src/senselab/utils/data_structures/model.py
  src/tests/audio/tasks/huggingface_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/voice_cloning_test.py
Labels: enhancement

#59 Release 0.3.0
  .github/workflows/docs.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  pyproject.toml
  src/senselab/audio/data_structures/audio.py
  src/senselab/audio/tasks/features_extraction/opensmile.py
  src/senselab/audio/tasks/features_extraction/praat_parselmouth.py
  src/senselab/audio/tasks/features_extraction/torchaudio.py
  src/senselab/audio/tasks/features_extraction/torchaudio_squim.py
  src/senselab/audio/tasks/plotting/plotting.py
  src/senselab/audio/tasks/speech_to_text/api.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/speech_to_text/speech_to_text.py
  src/senselab/audio/tasks/speech_to_text/transcript.py
  src/senselab/audio/tasks/voice_cloning/api.py
  src/senselab/audio/tasks/voice_cloning/knnvc.py
  src/senselab/audio/tasks/voice_cloning/voice_cloning.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transofmers_embeddings_extraction.py
  src/senselab/utils/data_structures/device.py
  src/senselab/utils/data_structures/huggingface.py
  src/senselab/utils/data_structures/language.py
  src/senselab/utils/data_structures/model.py
  src/senselab/utils/tasks/input_output.py
  src/tests/audio/tasks/features_extraction_test.py
  src/tests/audio/tasks/huggingface_test.py
  src/tests/audio/tasks/language_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/voice_cloning_test.py
Labels: release, minor

#64 Release 0.3.0 - let's go
  .github/workflows/test.yaml
Labels: release, minor

#66 making release process lighter
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  pyproject.toml
  src/tests/audio/tasks/voice_cloning_test.py
Labels: release, minor

#70 Senselab io
  pyproject.toml
  src/senselab/audio/data_structures/audio.py
  src/senselab/utils/data_structures/dataset.py
  src/senselab/utils/tasks/input_output.py
  src/senselab/video/data_structures/video.py
  src/senselab/video/tasks/input_output.py
  src/tests/utils/data_structures/dataset_test.py
Labels: enhancement

#74 VAD and speaker diarization
  CONTRIBUTING.md
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speaker_diarization/pyannote.py
  src/senselab/audio/tasks/speaker_diarization/pyannote_speaker_diarization.py
  src/senselab/audio/tasks/speech_to_text/api.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/speech_to_text/transcript.py
  src/senselab/audio/tasks/voice_activity_detection/api.py
  src/senselab/utils/data_structures/script_line.py
  src/senselab/utils/tasks/input_output.py
  src/tests/audio/tasks/speaker_diarization_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/voice_activity_detection_test.py
Labels: enhancement

#78 adding speech enhancement task
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speaker_diarization/pyannote.py
  src/senselab/audio/tasks/speaker_embeddings/api.py
  src/senselab/audio/tasks/speaker_embeddings/speechbrain.py
  src/senselab/audio/tasks/speech_enhancement/__init__.py
  src/senselab/audio/tasks/speech_enhancement/api.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/voice_activity_detection/api.py
  src/senselab/audio/tasks/voice_cloning/api.py
  src/senselab/audio/tasks/voice_cloning/knnvc.py
  src/tests/__init__.py
  src/tests/audio/__init__.py
  src/tests/audio/conftest.py
  src/tests/audio/data_structures/__init__.py
  src/tests/audio/data_structures/audio_test.py
  src/tests/audio/tasks/__init__.py
  src/tests/audio/tasks/classification_test.py
  src/tests/audio/tasks/data_augmentation_test.py
  src/tests/audio/tasks/features_extraction_test.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speaker_diarization_test.py
  src/tests/audio/tasks/speaker_embeddings_test.py
  src/tests/audio/tasks/speech_enhancement_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/voice_activity_detection_test.py
  src/tests/audio/tasks/voice_cloning_test.py
  src/tests/utils/__init__.py
  src/tests/utils/data_structures/__init__.py
  src/tests/utils/data_structures/language_test.py
  src/tests/utils/data_structures/model_test.py
  src/tests/utils/tasks/__init__.py
Labels: enhancement

#80 adding the text to speech task
  src/senselab/audio/tasks/text_to_speech/__init__.py
  src/senselab/audio/tasks/text_to_speech/api.py
  src/senselab/audio/tasks/text_to_speech/huggingface.py
  src/tests/audio/tasks/text_to_speech_test.py
Labels: enhancement

#81 Add dimensionality reduction task
  pyproject.toml
  src/senselab/utils/tasks/dimensionality_reduction.py
  src/tests/utils/tasks/dimensionality_reduction_test.py
Labels: enhancement

#79 adding text embeddings extraction with sentencetransformers
  src/senselab/text/tasks/__init__.py
  src/senselab/text/tasks/embeddings_extraction/api.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transformers.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transofmers_embeddings_extraction.py
  src/tests/text/conftest.py
  src/tests/text/tasks/embeddings_extraction_test.py
Labels: enhancement

#82 Release 050
  CONTRIBUTING.md
  FEATURES.tmp.md
  pyproject.toml
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speaker_diarization/pyannote.py
  src/senselab/audio/tasks/speaker_embeddings/api.py
  src/senselab/audio/tasks/speaker_embeddings/speechbrain.py
  src/senselab/audio/tasks/speech_enhancement/__init__.py
  src/senselab/audio/tasks/speech_enhancement/api.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/ssl_embeddings/__init__.py
  src/senselab/audio/tasks/ssl_embeddings/api.py
  src/senselab/audio/tasks/ssl_embeddings/self_supervised_features.py
  src/senselab/audio/tasks/text_to_speech/__init__.py
  src/senselab/audio/tasks/text_to_speech/api.py
  src/senselab/audio/tasks/text_to_speech/huggingface.py
  src/senselab/audio/tasks/voice_activity_detection/api.py
  src/senselab/audio/tasks/voice_cloning/api.py
  src/senselab/audio/tasks/voice_cloning/knnvc.py
  src/senselab/text/tasks/__init__.py
  src/senselab/text/tasks/embeddings_extraction/api.py
  src/senselab/text/tasks/embeddings_extraction/huggingface.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transformers.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transofmers_embeddings_extraction.py
  src/senselab/utils/data_structures/model.py
  src/senselab/utils/tasks/dimensionality_reduction.py
  src/tests/__init__.py
  src/tests/audio/__init__.py
  src/tests/audio/conftest.py
  src/tests/audio/data_structures/__init__.py
  src/tests/audio/data_structures/audio_test.py
  src/tests/audio/tasks/__init__.py
  src/tests/audio/tasks/classification_test.py
  src/tests/audio/tasks/data_augmentation_test.py
  src/tests/audio/tasks/features_extraction_test.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speaker_diarization_test.py
  src/tests/audio/tasks/speaker_embeddings_test.py
  src/tests/audio/tasks/speech_enhancement_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/text_to_speech_test.py
  src/tests/audio/tasks/voice_activity_detection_test.py
  src/tests/audio/tasks/voice_cloning_test.py
  src/tests/text/conftest.py
  src/tests/text/tasks/embeddings_extraction_test.py
  src/tests/utils/__init__.py
  src/tests/utils/data_structures/__init__.py
  src/tests/utils/data_structures/language_test.py
  src/tests/utils/data_structures/model_test.py
  src/tests/utils/tasks/__init__.py
  src/tests/utils/tasks/dimensionality_reduction_test.py
Labels: release, minor

#83 fixing documentation issue
  .github/workflows/docs.yaml
Labels: enhancement, release, patch

#84 attempting to fix documentation
  src/senselab/audio/tasks/speaker_diarization/pyannote.py
  src/senselab/utils/data_structures/model.py
Labels: enhancement
