Repository sensein/senselab, pull requests merged in 2024-07, with the labels that each got.

#87 Add b2ai speaker verification functions
  audio_48khz_mono_16bits.wav
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_verification/__init__.py
  src/senselab/audio/tasks/speaker_verification/speaker_verification.py
  src/tests/audio/tasks/speaker_verification_test.py
Labels: enhancement

#92 release 0.6.0 is for fixing bugs and adjusting docs
  .github/workflows/docs.yaml
  .gitignore
  .pre-commit-config.yaml
  audio_48khz_mono_16bits.wav
  pyproject.toml
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_verification/__init__.py
  src/senselab/audio/tasks/speaker_verification/speaker_verification.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/tests/audio/tasks/speaker_verification_test.py
  tutorials/getting_started.ipynb
Labels: release, minor

#96 :sparkles: add pooling methods
  src/senselab/utils/tasks/pooling.py
  src/tests/utils/tasks/pooling_test.py
Labels: enhancement

#97 Add documentation for speaker embeddings task and fix audio length bug
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_embeddings/api.py
  src/senselab/audio/tasks/speaker_embeddings/speechbrain.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/tests/audio/conftest.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speaker_embeddings_test.py
  src/tests/audio/tasks/speech_enhancement_test.py
  tutorials/extract_speaker_embeddings_tutorial.ipynb
Labels: documentation, enhancement

#113 pre_commit_experiments
  .github/workflows/test.yaml
  CONTRIBUTING.md
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speech_enhancement/api.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/text_to_speech/api.py
  src/senselab/audio/tasks/text_to_speech/huggingface.py
  src/senselab/audio/tasks/voice_activity_detection/api.py
  src/senselab/text/tasks/__init__.py
  src/senselab/text/tasks/embeddings_extraction/api.py
  src/senselab/text/tasks/embeddings_extraction/huggingface.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transformers.py
  src/senselab/utils/data_structures/model.py
  src/senselab/utils/data_structures/script_line.py
  src/tests/__init__.py
  src/tests/audio/data_structures/audio_test.py
  src/tests/audio/tasks/features_extraction_test.py
  src/tests/audio/tasks/speaker_diarization_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/text_to_speech_test.py
  src/tests/audio/tasks/voice_activity_detection_test.py
  src/tests/audio/tasks/voice_cloning_test.py
  src/tests/text/conftest.py
  src/tests/text/tasks/embeddings_extraction_test.py
Labels: enhancement

#93 adjusting dependencies and github actions plus adding pooling methods as a task plus fixing speechbrain issues plus adding some documentation
  .github/workflows/test.yaml
  CONTRIBUTING.md
  README.md
  audio_48khz_mono_16bits.wav
  pyproject.toml
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speaker_embeddings/api.py
  src/senselab/audio/tasks/speaker_embeddings/speechbrain.py
  src/senselab/audio/tasks/speech_enhancement/api.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/text_to_speech/api.py
  src/senselab/audio/tasks/text_to_speech/huggingface.py
  src/senselab/audio/tasks/voice_activity_detection/api.py
  src/senselab/text/tasks/__init__.py
  src/senselab/text/tasks/embeddings_extraction/api.py
  src/senselab/text/tasks/embeddings_extraction/huggingface.py
  src/senselab/text/tasks/embeddings_extraction/sentence_transformers.py
  src/senselab/utils/data_structures/model.py
  src/senselab/utils/data_structures/script_line.py
  src/senselab/utils/tasks/pooling.py
  src/tests/__init__.py
  src/tests/audio/conftest.py
  src/tests/audio/data_structures/audio_test.py
  src/tests/audio/tasks/features_extraction_test.py
  src/tests/audio/tasks/preprocessing_test.py
  src/tests/audio/tasks/speaker_diarization_test.py
  src/tests/audio/tasks/speaker_embeddings_test.py
  src/tests/audio/tasks/speech_enhancement_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  src/tests/audio/tasks/text_to_speech_test.py
  src/tests/audio/tasks/voice_activity_detection_test.py
  src/tests/audio/tasks/voice_cloning_test.py
  src/tests/text/conftest.py
  src/tests/text/tasks/embeddings_extraction_test.py
  src/tests/utils/tasks/pooling_test.py
  tutorials/.gitkeep
  tutorials/extract_speaker_embeddings_tutorial.ipynb
Labels: enhancement, release, patch

#115 Pydra
  src/senselab/__init__.py
  src/senselab/audio/tasks/classification/speech_emotion_recognition.py
  src/senselab/utils/data_structures/dataset.py
  src/senselab/utils/data_structures/device.py
  src/senselab/utils/data_structures/pydra_helpers.py
  src/tests/utils/data_structures/pydra_helpers_test.py
Labels: release, patch

#114 Update pyproject.toml
  .github/workflows/test.yaml
  pyproject.toml
Labels: release, patch

#94 Add and improve documentation for dimensionality reduction
  src/senselab/utils/tasks/dimensionality_reduction.py
  src/senselab/utils/tasks/dimensionality_reduction_table.md
  tutorials/dimensionality_reduction_tutorial.ipynb
Labels: documentation, enhancement, release, patch

#119 109 review and test speech to text task
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  README.md
  docs_style/pdoc-theme/syntax-highlighting.css
  docs_style/pdoc-theme/theme.css
  index.rst
  pyproject.toml
  src/senselab/app.py
  src/senselab/audio-cli/.gitkeep
  src/senselab/audio/__init__.py
  src/senselab/audio/data_structures/__init__.py
  src/senselab/audio/data_structures/audio.py
  src/senselab/audio/tasks/__init__.py
  src/senselab/audio/tasks/speech_to_text/__init__.py
  src/senselab/audio/tasks/speech_to_text/api.py
  src/senselab/audio/tasks/speech_to_text/doc.md
  src/senselab/audio/tasks/speech_to_text/huggingface.py
  src/senselab/audio/tasks/speech_to_text_evaluation/__init__.py
  src/senselab/audio/tasks/speech_to_text_evaluation/doc.md
  src/senselab/audio/tasks/speech_to_text_evaluation/utils.py
  src/senselab/cli.py
  src/senselab/text/__init__.py
  src/senselab/utils/__init__.py
  src/senselab/utils/data_structures/logging.py
  src/senselab/utils/data_structures/model.py
  src/senselab/utils/tasks/plotting.py
  src/senselab/video/__init__.py
  src/tests/app_test.py
  src/tests/audio/conftest.py
  src/tests/audio/tasks/speech_to_text_evaluation_test.py
  src/tests/audio/tasks/speech_to_text_test.py
  tutorials/extract_speaker_embeddings.ipynb
  tutorials/getting_started.ipynb
  tutorials/speech_to_text.ipynb
Labels: enhancement

#89 14 add forced alignment
  .pre-commit-config.yaml
  pyproject.toml
  src/senselab/audio/tasks/forced_alignment/__init__.py
  src/senselab/audio/tasks/forced_alignment/constants.py
  src/senselab/audio/tasks/forced_alignment/data_structures.py
  src/senselab/audio/tasks/forced_alignment/forced_alignment.py
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/utils/data_structures/model.py
  src/tests/audio/tasks/forced_alignment_test.py
  src/tests/audio/tasks/preprocessing_test.py
Labels: enhancement, release, minor

#121 fixing link to tutorials and documentation style
  src/senselab/audio/tasks/speech_to_text/doc.md
  src/senselab/audio/tasks/speech_to_text_evaluation/doc.md
Labels: documentation, enhancement, release, patch

#123 Changing the style of the doc (dark mode)
  .pre-commit-config.yaml
  docs_style/pdoc-theme/theme.css
  src/senselab/audio/tasks/speaker_embeddings/api.py
Labels: documentation, enhancement, release, patch

#125 Fixing doc style (adding button style)
  docs_style/pdoc-theme/syntax-highlighting.css
  src/senselab/audio/tasks/speaker_embeddings/doc.md
  src/senselab/audio/tasks/speech_to_text/doc.md
  src/senselab/audio/tasks/speech_to_text_evaluation/doc.md
Labels: documentation, enhancement, release, patch
