Repository sensein/senselab, pull requests merged in 2024-08, with the labels that each got.

#131 fixing bug in script line
  src/senselab/utils/data_structures/script_line.py
Labels: bug, release, patch

#105 Review and test speech-enhancement
  .github/dependabot.yaml
  .pre-commit-config.yaml
  src/senselab/audio/tasks/speech_enhancement/__init__.py
  src/senselab/audio/tasks/speech_enhancement/api.py
  src/senselab/audio/tasks/speech_enhancement/doc.md
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/senselab/utils/data_structures/device.py
  src/tests/audio/conftest.py
  src/tests/audio/tasks/speech_enhancement_test.py
  tutorials/speech_enhancement.ipynb
Labels: documentation, release, patch

#135 updating actions down and upload artifact to v4
  .github/workflows/docs.yaml
Labels: release, patch, dependencies

#136 Adding documentation and tutorial and logger to voice activity detection and speaker diarization
  src/senselab/audio/tasks/speaker_diarization/__init__.py
  src/senselab/audio/tasks/speaker_diarization/api.py
  src/senselab/audio/tasks/speaker_diarization/doc.md
  src/senselab/audio/tasks/speaker_diarization/pyannote.py
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/senselab/audio/tasks/voice_activity_detection/__init__.py
  src/senselab/audio/tasks/voice_activity_detection/doc.md
  src/senselab/utils/tasks/plotting.py
  tutorials/speaker_diarization.ipynb
  tutorials/voice_activity_detection.ipynb
Labels: documentation, enhancement, release, patch

#137 adding testmon as a dev dependency
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  src/tests/audio/tasks/text_to_speech_test.py
Labels: release, patch, dependencies

#132 110 review and test voice cloning task
  src/senselab/audio/tasks/preprocessing/preprocessing.py
  src/senselab/audio/tasks/voice_cloning/__init__.py
  src/senselab/audio/tasks/voice_cloning/api.py
  src/senselab/audio/tasks/voice_cloning/doc.md
  src/senselab/audio/tasks/voice_cloning/knnvc.py
  src/tests/audio/tasks/voice_cloning_test.py
  tutorials/voice_cloning.ipynb
Labels: documentation, enhancement, release, minor

#149 Dataset update
  src/senselab/utils/data_structures/dataset.py
  src/tests/utils/data_structures/dataset_test.py
Labels: documentation, enhancement, release, minor

#138 127 add timestamped transcription workflow
  src/senselab/audio/workflows/__init__.py
  src/senselab/audio/workflows/transcribe_timestamped/__init__.py
  src/senselab/audio/workflows/transcribe_timestamped/transcribe_timestamped.py
  src/senselab/utils/tasks/batching.py
  src/tests/audio/workflows/transcribe_timestamped_test.py
  src/tests/utils/tasks/batching_test.py
  tutorials/transcribe_timestamped_tutorial.ipynb
Labels: enhancement, release, minor
