Repository sensein/senselab, pull requests merged in 2025-01, with the labels that each got.

#241 fixing broken colab link
  tutorials/audio/speaker_verification.ipynb
Labels: bug, documentation

#242 fixing import in the speaker emebeddings tutorial
  tutorials/audio/extract_speaker_embeddings.ipynb
Labels: bug, documentation

#203 Media Pipe Pose Estimation + Visualization
  pyproject.toml
  src/senselab/video/data_structures/__init__.py
  src/senselab/video/data_structures/pose.py
  src/senselab/video/tasks/__init__.py
  src/senselab/video/tasks/pose_estimation/__init__.py
  src/senselab/video/tasks/pose_estimation/api.py
  src/senselab/video/tasks/pose_estimation/doc.md
  src/senselab/video/tasks/pose_estimation/estimate.py
  src/senselab/video/tasks/pose_estimation/utils.py
  src/senselab/video/tasks/pose_estimation/visualization.py
  src/tests/data_for_testing/pose_data/no_people.jpeg
  src/tests/data_for_testing/pose_data/single_person.jpg
  src/tests/data_for_testing/pose_data/three_people.jpg
  src/tests/video/data_structures/pose_test.py
  src/tests/video/tasks/pose_estimation_test.py
  tutorials/video/pose_estimation.ipynb
Labels: enhancement, release, minor, to-test, to-test-gpu

#234 Test Device Truly Available by Creating Trivial Object
  src/senselab/utils/data_structures/device.py
Labels: bug, release, patch, to-test, to-test-gpu

#244 enhancing speech enhancement
  pyproject.toml
  src/senselab/audio/tasks/speech_enhancement/speechbrain.py
  src/tests/audio/tasks/speech_enhancement_test.py
  src/tests/utils/data_structures/pydra_helpers_test.py
  src/tests/video/tasks/pose_estimation_test.py
  tutorials/audio/00_getting_started.ipynb
  tutorials/audio/speaker_verification.ipynb
  tutorials/audio/speech_enhancement.ipynb
  tutorials/video/pose_estimation.ipynb
Labels: bug, enhancement, release, minor, to-test, to-test-gpu
