Repository sensein/senselab, pull requests merged in 2025-04, with the labels that each got.

#284 Added Audio.from_stream + enhanced Audio.from_filepath
  .github/workflows/tests.yaml
  CONTRIBUTING.md
  README.md
  src/senselab/audio/data_structures/audio.py
  src/tests/audio/data_structures/audio_test.py
  tutorials/audio/00_getting_started.ipynb
Labels: enhancement, release, minor, to-test, to-test-gpu

#294 Enhanced stability for cca and cka
  src/senselab/utils/tasks/cca_cka.py
Labels: release, patch, to-test, to-test-gpu

#308 removing timestamped_transcript workflow
  src/senselab/audio/workflows/transcribe_timestamped/__init__.py
  src/senselab/audio/workflows/transcribe_timestamped/transcribe_timestamped.py
  src/tests/audio/workflows/transcribe_timestamped_test.py
  tutorials/audio/transcribe_timestamped.ipynb
Labels: to-test, to-test-gpu

#310 Feats documentation refactor
  .github/workflows/docs.yaml
  pyproject.toml
  src/senselab/audio/tasks/features_extraction/doc.md
  src/senselab/utils/data_structures/model.py
Labels: documentation, release, patch

#313 added coqui-tts for text to speech
  src/senselab/audio/tasks/text_to_speech/api.py
  src/senselab/audio/tasks/text_to_speech/coqui.py
  src/senselab/audio/tasks/text_to_speech/doc.md
  src/tests/audio/tasks/text_to_speech_test.py
  tutorials/audio/text_to_speech.ipynb
Labels: release, minor, to-test, to-test-gpu

#314 Update README.md getting started link
  README.md
Labels: documentation

#318 prevent model loading while importing plot_waveform.
  src/senselab/audio/tasks/plotting/plotting.py
Labels: release, patch, to-test, to-test-gpu
